### ISSUE TITLE
Can't Move to Global Usings > Document for every usings in cs file

### ISSUE THREAD

**Issue by philippedurocher** [magiak/GlobalUsingsAnalyzer#1]
Hi, I have a small problem with the analyzer. 
![image](https://user-images.githubusercontent.com/1459389/218340304-89b0ae51-2ddc-407b-aea0-cd4b0ae5f949.png)

When I try to Move to Global Usings and I select 'Document', I get an empty preview screen :
![image](https://user-images.githubusercontent.com/1459389/218340350-f9feb354-612e-468d-a7b7-087289449337.png)

I would like to be able to move every usings from a csharp file to global usings with a single command.

Thank you.

**Comment by philippedurocher** [comment]
Sorry you can delete my issue. I restarted VS and now everything is working. Should have done that before posting. 🙄

**Comment by magiak** [comment]
Hi, no problem. I am glad that you was able to solve it :)
